language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: GvX6+1gyuajcoIXiH1H/z86smx/qHfw9Eu5PMBLLT0dTUMwml5n+CrctNMI8c56QxnnLHkk+kMj9S22osU3MsWRl8zHpzE6ON9eGIV8tx7EsMEpcC+Ka7WJYA2aCn/K0nk4e9X41sPTFYrTmecXwl116xZarePiMNc1c6ynKbIN7hKhftWt89MwDvBL9F/+13zAjwtBmXZDgXUJOTuUPrv2zabaA/xZj1cna7q9u+wndFVisEnmPgMG1nQE2gBhgSm8hmXQGs6N9jLkky5w70+RhhGmNJb5QPhFTdrm6a1xQw+oTM6Ag5hdkCVWm+qIti4K+0/LuwJW55Rggs9e3mvhwgkZ7lBpHGxW7SaHf68ryKDNOydQnlKP/N6/mqvLPhKSPiY11gZaGg/x9weQuNi0/rVj1YI/4yTq4VwccMmuYCErwqtlpWP5U8TkpWojTRmqVQqmkz/OosSVS1V09ZT19Xe84HmggBX/COfychu6tPOPL0StVy5bk28tjo0HDWMndHcXbZ1macwS2AXXwsLcqzZtk/re8bMacYif7DFqF594PSa75Rlc78pCHtcRAHUJ+J58e9kw8qXy2c4aV2wGjyuq5Veh6FOjai1biJFaxiInKljxOFGFyCOfpngjrIPfE2nQbZRfXP41Rs2KkMXPvXAS4IbaC2oPzhaOgv/0=
  app: spotify-react-app
  on:
    repo: leoparis89/spotify-react-app
