language: node_js
node_js:
- '8'
deploy:
  api_key:
    provider: heroku
    secure: Ddp1ZXcLhNGw2ppfjZyGzHQ8wZmmOGDE5UCSqB8MQS+lu5QLiVzYDjXNS6vvkqV41BrUl6FQ2WFT4smv9BbVTBF33VXlVZYvoZiMwJhRjbfoxEzquQ67tEXrJIbngEmNlnvSm0ZgAxrDM52iTbfv5QsFzdNdaG1lJQMGigH8UtJeeNXJ6hepg/91AttP+DxYBrJ72MgdhjR6qZj+IuNKYdt4oJejcRD30cBirGSBWdLbVieRbnqbfI49KRJQjYCPMBCuMuyggmhuFQE3Y+3iW5EjAGTzUU+RmRz5AEBY4N45dUFlQCKsiCAH/3UfQwckMtew0b4LNu/IOz8yMTQDccRz0MUX3eTwXi8xOKviBUmk7CjWuYAAmFL8sAibDusS2BsviaifrxRxP47ETn6EIWuzpnlC2lP6vl+kyyspWmY75rwS3FIZcdlyaDsKCzGHyx0DBKRSm7+WECIXswb5TPlQVZb9+7RMVSPOJSzJVc9z8FFdZUPgroP7jxHCpcycdYTvcWPocJgDgwZ7aOPY9a00XAT/DgqIUeJiQgdLKZsF1Duyt5EMSZSpPeG6+rpYCmJhSVK4uQE62JEPNyUk7AU4BiL8fmIAC9DNl3Du0bf/GVv3wkU7RnC4FDGCZvhkjvIu5hpcuG/LNxI9vuOgUqUdNbjidkC4bqVjEs6ripM=
